# Generated by Django 3.1.3 on 2020-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/image/data/employeerole', verbose_name='Изображение'),
        ),
    ]
