# Generated by Django 3.1.3 on 2020-12-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeerole_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
