# Generated by Django 3.1.3 on 2020-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModeTDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания цены')),
                ('effective_date', models.DateTimeField(verbose_name='Дата вступления в силу')),
            ],
            options={
                'verbose_name': 'Цена одного пройденого километра транспортом',
                'verbose_name_plural': 'Прайс-лист одного пройденого километра транспортом',
            },
        ),
        migrations.CreateModel(
            name='PriceModeTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания цены')),
                ('effective_date', models.DateTimeField(verbose_name='Дата вступления в силу')),
            ],
            options={
                'verbose_name': 'Цена часа аренды транспорта',
                'verbose_name_plural': 'Прайс-лист часа аренды транспорта',
            },
        ),
        migrations.CreateModel(
            name='PricePacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания цены')),
                ('effective_date', models.DateTimeField(verbose_name='Дата вступления в силу')),
            ],
            options={
                'verbose_name': 'Цена единицы упаковочного материала',
                'verbose_name_plural': 'Прайс-лист единицы упаковочного материала',
            },
        ),
        migrations.CreateModel(
            name='PriceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания цены')),
                ('effective_date', models.DateTimeField(verbose_name='Дата вступления в силу')),
            ],
            options={
                'verbose_name': 'Цена часа найма работников',
                'verbose_name_plural': 'Прайс-лист часа найма работников',
            },
        ),
    ]
