# Generated by Django 3.1.3 on 2020-11-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricelist', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        ('transport', '0001_initial'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerole',
            name='creater',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', verbose_name='Установил цену'),
        ),
        migrations.AddField(
            model_name='pricerole',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='pricepacking',
            name='creater',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', verbose_name='Установил цену'),
        ),
        migrations.AddField(
            model_name='pricepacking',
            name='packing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packing.packing', verbose_name='Упаковочный материал'),
        ),
        migrations.AddField(
            model_name='pricemodetransport',
            name='creater',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', verbose_name='Установил цену'),
        ),
        migrations.AddField(
            model_name='pricemodetransport',
            name='mode_transport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.modetransport', verbose_name='Вид транспорта'),
        ),
        migrations.AddField(
            model_name='pricemodetdistance',
            name='creater',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee', verbose_name='Установил цену'),
        ),
        migrations.AddField(
            model_name='pricemodetdistance',
            name='mode_transport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.modetransport', verbose_name='Вид транспорта'),
        ),
    ]
