# Generated by Django 3.1.3 on 2020-12-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
        ('transport', '0002_auto_20201127_1826'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pricelist', '0002_auto_20201127_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodetdistance',
            name='mode_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.modetransport', verbose_name='Вид транспорта'),
        ),
        migrations.AlterField(
            model_name='pricemodetransport',
            name='mode_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.modetransport', verbose_name='Вид транспорта'),
        ),
        migrations.AlterField(
            model_name='pricepacking',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.packing', verbose_name='Упаковочный материал'),
        ),
        migrations.AlterField(
            model_name='pricerole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
    ]
