# Generated by Django 3.1.3 on 2020-12-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_auto_20201206_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemodetransport',
            options={'ordering': ['effective_date', 'date_of_creation'], 'verbose_name': 'Цена часа аренды транспорта', 'verbose_name_plural': 'Прайс-лист часа аренды транспорта'},
        ),
    ]
