# Generated by Django 3.1.3 on 2020-12-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_auto_20201206_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemodetransport',
            options={'verbose_name': 'Цена часа аренды транспорта', 'verbose_name_plural': 'Прайс-лист часа аренды транспорта'},
        ),
    ]
