# Generated by Django 3.1.3 on 2020-12-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0007_auto_20201206_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemodetdistance',
            options={'ordering': ['-effective_date', '-date_of_creation'], 'verbose_name': 'Цена одного пройденого километра транспортом', 'verbose_name_plural': 'Прайс-лист одного пройденого километра транспортом'},
        ),
        migrations.AlterModelOptions(
            name='pricemodetransport',
            options={'ordering': ['-effective_date', '-date_of_creation'], 'verbose_name': 'Цена часа аренды транспорта', 'verbose_name_plural': 'Прайс-лист часа аренды транспорта'},
        ),
        migrations.AlterModelOptions(
            name='pricepacking',
            options={'ordering': ['-effective_date', '-date_of_creation'], 'verbose_name': 'Цена единицы упаковочного материала', 'verbose_name_plural': 'Прайс-лист единицы упаковочного материала'},
        ),
        migrations.AlterModelOptions(
            name='pricerole',
            options={'ordering': ['-effective_date', '-date_of_creation'], 'verbose_name': 'Цена часа найма работников', 'verbose_name_plural': 'Прайс-лист часа найма работников'},
        ),
        migrations.RenameField(
            model_name='pricemodetdistance',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='pricemodetransport',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='pricepacking',
            old_name='total_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='pricerole',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
