# Generated by Django 3.1.3 on 2020-11-27 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantForMARequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Выбор сотрудник на помощь с переездом',
                'verbose_name_plural': 'Выбор сотрудников на помощь с переездом',
                'ordering': ['move_assistance_request'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeForMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_hours', models.PositiveSmallIntegerField(verbose_name='Количество часов найма')),
            ],
            options={
                'verbose_name': 'Выбор сотрудника на выполнение переезда',
                'verbose_name_plural': 'Выбор сотрудников на выполнение переезда',
                'ordering': ['move_request'],
            },
        ),
        migrations.CreateModel(
            name='MoveAssistanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pen', 'В ожидании рассмотрения'), ('con', 'Подтверждёна'), ('ipr', 'В процессе выполнения'), ('com', 'Завершена'), ('can', 'Отменена'), ('rej', 'Отклонена')], default='pen', help_text='Выберите статус заказа', max_length=3, verbose_name='Статус заказа')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('full_name', models.CharField(help_text='Введите ФИО клиента', max_length=255, verbose_name='ФИО клиента')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('time_type', models.CharField(choices=[('m', 'Утром'), ('d', 'Днём'), ('e', 'Вечером'), ('n', 'Ночью'), ('o', 'Точное время')], default='m', max_length=1, verbose_name='Время выполнения заказа')),
                ('date_of_completion', models.DateField(verbose_name='Дата приезда')),
                ('time_of_completion', models.TimeField(blank=True, verbose_name='Дата приезда')),
                ('comment', models.TextField(blank=True, help_text='Введите примечания по заказу', verbose_name='Комментарий')),
                ('client_adress', models.CharField(help_text='Введите адрес клиента', max_length=20, verbose_name='Адрес клиента')),
            ],
            options={
                'verbose_name': 'Заявка на помощь с переездом',
                'verbose_name_plural': 'Заявки на помощь с переездом',
            },
        ),
        migrations.CreateModel(
            name='MoveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_confirm', models.DateTimeField(auto_now_add=True, verbose_name='Дата потверждения')),
                ('receiving_packaging', models.CharField(choices=[('p', 'Самовывоз'), ('g', 'Получение при выполнение заказа')], default='p', max_length=1, verbose_name='Тип получения упаковки')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая стоимость заказа')),
                ('payment_type', models.CharField(choices=[('c', 'Наличный рассчет при выполнении заказа'), ('n', 'Безналичный рассчет')], default='pen', max_length=1, verbose_name='Тип опплаты')),
            ],
            options={
                'verbose_name': 'Заказ на переезд',
                'verbose_name_plural': 'Заказы на переезд',
                'ordering': ['date_of_confirm'],
            },
        ),
        migrations.CreateModel(
            name='MoveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pen', 'В ожидании рассмотрения'), ('con', 'Подтверждёна'), ('ipr', 'В процессе выполнения'), ('com', 'Завершена'), ('can', 'Отменена'), ('rej', 'Отклонена')], default='pen', help_text='Выберите статус заказа', max_length=3, verbose_name='Статус заказа')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('full_name', models.CharField(help_text='Введите ФИО клиента', max_length=255, verbose_name='ФИО клиента')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=20, verbose_name='Номер телефона')),
                ('time_type', models.CharField(choices=[('m', 'Утром'), ('d', 'Днём'), ('e', 'Вечером'), ('n', 'Ночью'), ('o', 'Точное время')], default='m', max_length=1, verbose_name='Время выполнения заказа')),
                ('date_of_completion', models.DateField(verbose_name='Дата приезда')),
                ('time_of_completion', models.TimeField(blank=True, verbose_name='Дата приезда')),
                ('comment', models.TextField(blank=True, help_text='Введите примечания по заказу', verbose_name='Комментарий')),
                ('creater', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал заявку')),
            ],
            options={
                'verbose_name': 'Заявка на переезд',
                'verbose_name_plural': 'Заявки на переезд',
            },
        ),
        migrations.CreateModel(
            name='TransportForMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_hours', models.PositiveSmallIntegerField(verbose_name='Количество часов аренды')),
                ('mode_transport', models.ForeignKey(help_text='Выберите вид транспорта, который необходим для выполнения заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_with_mode_transport', to='transport.modetransport', verbose_name='Вид транспорта')),
                ('move_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_for_move', to='orders.moverequest', verbose_name='Заказ на переезд')),
                ('transport', models.ForeignKey(help_text='Выберите транспорт, который необходим для выполнения заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_with_transport', to='transport.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Выбор транспорта на выполнение переезда',
                'verbose_name_plural': 'Выбор транспорта на выполнение переезда',
                'ordering': ['move_request'],
            },
        ),
        migrations.CreateModel(
            name='RouteMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_a', models.CharField(max_length=255, verbose_name='Адрес погрузки вещей')),
                ('point_b', models.CharField(max_length=255, verbose_name='Адрес разгрузки вещей')),
                ('distance', models.PositiveSmallIntegerField(verbose_name='Дистанция между адресами (в км.)')),
                ('move_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_for_move', to='orders.moverequest', verbose_name='Заказ на переезд')),
            ],
            options={
                'verbose_name': 'Марщрут переезда',
                'verbose_name_plural': 'Марщруты переездов',
                'ordering': ['move_request'],
            },
        ),
        migrations.CreateModel(
            name='PackingForMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('move_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_for_move', to='orders.moverequest', verbose_name='Заказ на переезд')),
                ('packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_with_packing', to='packing.packing', verbose_name='Упаковочный материал')),
            ],
            options={
                'verbose_name': 'Выбор упаковочного материала на выполнение переезда',
                'verbose_name_plural': 'Выбор упаковочного материала на выполнение переезда',
                'ordering': ['move_request'],
            },
        ),
    ]
