# Generated by Django 3.1.3 on 2020-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201127_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveassistancerequest',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=18, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='moveassistancerequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, verbose_name='Время приезда'),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=18, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, verbose_name='Время приезда'),
        ),
    ]
