# Generated by Django 3.1.3 on 2020-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201127_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveassistancerequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приезда'),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, null=True, verbose_name='Время приезда'),
        ),
    ]
