# Generated by Django 3.1.3 on 2020-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201129_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveorder',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='moveorder',
            name='receiving_packaging',
        ),
        migrations.AddField(
            model_name='moverequest',
            name='payment_type',
            field=models.CharField(choices=[('c', 'Наличный рассчет при выполнении заказа'), ('n', 'Безналичный рассчет')], default='pen', max_length=1, verbose_name='Тип опплаты'),
        ),
        migrations.AddField(
            model_name='moverequest',
            name='receiving_packaging',
            field=models.CharField(choices=[('p', 'Самовывоз'), ('g', 'Получение при выполнение заказа')], default='p', max_length=1, verbose_name='Тип получения упаковки'),
        ),
    ]
