# Generated by Django 3.1.3 on 2020-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201129_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverequest',
            name='payment_type',
            field=models.CharField(choices=[('c', 'Наличный рассчет при выполнении заказа'), ('n', 'Безналичный рассчет')], default='c', max_length=1, verbose_name='Тип опплаты'),
        ),
    ]
