# Generated by Django 3.1.3 on 2020-12-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_employeeformoverequest_transportformoverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeformove',
            options={'ordering': ['move_order'], 'verbose_name': 'Выбор сотрудника на выполнение переезда', 'verbose_name_plural': 'Выбор сотрудников на выполнение переезда'},
        ),
        migrations.AlterModelOptions(
            name='transportformove',
            options={'ordering': ['move_order'], 'verbose_name': 'Выбор транспорта на выполнение переезда', 'verbose_name_plural': 'Выбор транспорта на выполнение переезда'},
        ),
        migrations.RemoveField(
            model_name='employeeformove',
            name='move_request',
        ),
        migrations.RemoveField(
            model_name='transportformove',
            name='move_request',
        ),
        migrations.AddField(
            model_name='employeeformove',
            name='move_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.moveorder', verbose_name='Заказ на переезд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportformove',
            name='move_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.moveorder', verbose_name='Заказ на переезд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packingformove',
            name='move_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_for_move', to='orders.moverequest', verbose_name='Заявка на переезд'),
        ),
        migrations.AlterField(
            model_name='routemove',
            name='move_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_for_move', to='orders.moverequest', verbose_name='Заявка на переезд'),
        ),
    ]
