# Generated by Django 3.1.3 on 2020-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201205_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveorder',
            name='date_of_confirm',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Дата потверждения'),
        ),
    ]
