# Generated by Django 3.1.3 on 2020-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20201206_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveorder',
            name='isCompleted',
            field=models.BooleanField(default=False, verbose_name='Заказ завершен'),
        ),
    ]
