# Generated by Django 3.1.3 on 2020-12-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_moveorder_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveorder',
            name='isCompleted',
        ),
        migrations.RemoveField(
            model_name='moveorder',
            name='isConfirm',
        ),
    ]
