# Generated by Django 3.1.3 on 2020-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20201206_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveassistancerequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, null=True, verbose_name='Точное время приезда'),
        ),
        migrations.AlterField(
            model_name='moveassistancerequest',
            name='time_type',
            field=models.CharField(choices=[('m', 'Утром'), ('d', 'Днём'), ('e', 'Вечером'), ('n', 'Ночью'), ('o', 'Точное время')], default='m', max_length=1, verbose_name='Время приезда'),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='time_of_completion',
            field=models.TimeField(blank=True, null=True, verbose_name='Точное время приезда'),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='time_type',
            field=models.CharField(choices=[('m', 'Утром'), ('d', 'Днём'), ('e', 'Вечером'), ('n', 'Ночью'), ('o', 'Точное время')], default='m', max_length=1, verbose_name='Время приезда'),
        ),
    ]
