# Generated by Django 3.1.3 on 2020-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20201206_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moverequest',
            name='receiving_packaging',
            field=models.CharField(choices=[('p', 'Самовывозом'), ('g', 'При выполнение заказа')], default='p', max_length=1, verbose_name='Получение упаковки'),
        ),
    ]
