# Generated by Django 3.1.3 on 2020-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modetransport',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image/data/transport', verbose_name='Изображение вида'),
        ),
    ]
