# Generated by Django 3.1.3 on 2020-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20201127_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modetransport',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/image/data/transport', verbose_name='Изображение вида'),
        ),
    ]
